Repository anitab-org/bridge-in-tech-backend, pull requests merged in 2020-06, with the labels that each got.

#3 docs: update README file
  README.md
Labels: Category: Documentation/Training, First Timers Only

#58 add ENV_SETUP_INSTRUCTION.md to .github folder
  .github/ENV_SETUP_INSTRUCTION.md
Labels: Category: Documentation/Training

#59 QA: test - user registration backend api
  .travis.yml
  app/api/models/user.py
  app/api/ms_api_utils.py
  app/api/resources/users.py
  config.py
  requirements.txt
  run.py
  tests/base_test_case.py
  tests/test_app_config.py
  tests/users/test_api_register.py
Labels: Category: Coding, Category: Quality Assurance, Program: GSOC
