Repository anitab-org/bridge-in-tech-backend, pull requests merged in 2020-10, with the labels that each got.

#167 Fix: Replace token access expiry to self-adjusting date
  tests/organizations/test_api_get_organization.py
  tests/organizations/test_api_list_organizations.py
  tests/organizations/test_api_update_organization.py
  tests/programs/test_api_create_program.py
  tests/programs/test_api_update_program.py
  tests/users/test_api_create_personal_background.py
  tests/users/test_api_create_user_additional_info.py
  tests/users/test_api_get_other_user_details.py
  tests/users/test_api_get_personal_background.py
  tests/users/test_api_get_user_additional_info.py
  tests/users/test_api_get_user_details.py
  tests/users/test_api_get_users_personal_details.py
  tests/users/test_api_login.py
  tests/users/test_api_update_personal_background.py
  tests/users/test_api_update_user_additional_info.py
  tests/users/test_api_update_user_details.py
Labels: Category: Coding, Status: Needs Review, Type: Bug, Type: Testing

#164 docs: updated setup instructions
  .github/ENV_SETUP_INSTRUCTION.md
Labels: Category: Documentation/Training, hacktoberfest-accepted

#169 refactor: Removed dependencies from requirements file
  requirements.txt
Labels: Category: Coding, dependencies, hacktoberfest-accepted

#174 docs: Added python badge
  README.md
Labels: hacktoberfest-accepted
