Repository anitab-org/bridge-in-tech-backend, pull requests merged in 2020-09, with the labels that each got.

#144 Doc: Created GETTING_STARTED.md file inside .github folder
  .github/GETTING_STARTED.md
Labels: Category: Documentation/Training

#125 Doc: Replace DB_REMOTE_URI to match setup inctruction
  .env.template
  config.py
Labels: Category: Coding, Category: Documentation/Training, Status: Needs Review

#130 Test: create program tests
  tests/organizations/test_api_create_program.py
Labels: Category: Coding, Status: Ready to Merge, Type: Testing

#137 Test: update program tests
  app/database/models/bit_schema/organization.py
  tests/programs/__init__.py
  tests/programs/test_api_update_program.py
Labels: Category: Quality Assurance, Status: Needs Review, Type: Testing

#138 Create config.yml file for welcome bot
  .github/config.yml
Labels: Category: Documentation/Training, Status: Needs Review

#139 Add missing images to BIT setup instructions Create main database sec…
  .github/ENV_SETUP_INSTRUCTION.md
Labels: Category: Documentation/Training, Status: Needs Review

#134 Fix: removes postgresql db uri MacOS specific syntax
  tests/test_app_config.py
Labels: Category: Quality Assurance, Status: Ready to Merge, Type: Testing

#156 Doc: update ENV_SETUP_INSTRUCTIONS for windows/ubuntu users
  .github/ENV_SETUP_INSTRUCTION.md
Labels: Category: Documentation/Training, Status: Needs Review
