Repository anitab-org/bridge-in-tech-backend, pull requests merged in 2021-04, with the labels that each got.

#222 HTTP code added
  app/api/resources/organizations.py
Labels: Category: Coding, Category: Documentation/Training, Open Source Hack, Status: Ready to Merge, Type: Maintenance

#251 docs:Link added in README.md
  README.md
Labels: Category: Documentation/Training, Open Source Hack, Status: Ready to Merge

#252 Corrected link in website
  docs/docusaurus.config.js
Labels: Category: Coding, Category: Documentation/Training, Open Source Hack, Status: Ready to Merge, Type: Bug

#214 chore : migrated to github actions and removed travis ci
  .github/workflows/main.yml
  .travis.yml
  config.py
Labels: Category: Coding, Status: Changes Requested, Type: Maintenance

#255 chore : added black and black's github action to format the code
  .github/workflows/black.yml
  README.md
  app/api/bit_extension.py
  app/api/dao/organization.py
  app/api/dao/personal_background.py
  app/api/dao/program.py
  app/api/dao/user_extension.py
  app/api/models/organization.py
  app/api/models/user.py
  app/api/request_api_utils.py
  app/api/resources/organizations.py
  app/api/resources/users.py
  app/api/validations/organization.py
  app/api/validations/user.py
  app/database/db_add_mock.py
  app/database/models/bit_schema/mentorship_relation_extension.py
  app/database/models/bit_schema/organization.py
  app/database/models/bit_schema/personal_background.py
  app/database/models/bit_schema/program.py
  app/database/models/bit_schema/user_extension.py
  app/database/models/ms_schema/mentorship_relation.py
  app/database/models/ms_schema/task_comment.py
  app/database/models/ms_schema/tasks_list.py
  app/database/models/ms_schema/user.py
  app/messages.py
  app/utils/bit_constants.py
  app/utils/bitschema_utils.py
  app/utils/date_converter.py
  app/utils/decorator_utils.py
  app/utils/ms_constants.py
  app/utils/validation_utils.py
  config.py
  run.py
  tests/base_test_case.py
  tests/organizations/test_api_get_organization.py
  tests/organizations/test_api_list_organizations.py
  tests/organizations/test_api_update_organization.py
  tests/programs/test_api_create_program.py
  tests/programs/test_api_update_program.py
  tests/programs/test_get_program.py
  tests/test_app_config.py
  tests/test_data.py
  tests/users/test_api_create_personal_background.py
  tests/users/test_api_create_user_additional_info.py
  tests/users/test_api_get_other_user_details.py
  tests/users/test_api_get_personal_background.py
  tests/users/test_api_get_user_additional_info.py
  tests/users/test_api_get_user_details.py
  tests/users/test_api_get_users_personal_details.py
  tests/users/test_api_login.py
  tests/users/test_api_register.py
  tests/users/test_api_update_personal_background.py
  tests/users/test_api_update_user_additional_info.py
  tests/users/test_api_update_user_details.py
Labels: Category: Coding, Category: Quality Assurance, Status: Needs Review, Type: Enhancement

#259 Docs: 229 update contributing
  .github/CONTRIBUTING.md
Labels: Open Source Hack, Status: Ready to Merge

#254 Docs: Add badges to docusaurus home.md
  docs/docs/Home.md
Labels: Category: Documentation/Training, Open Source Hack, Status: Ready to Merge

#263 [Chore] Update GitHub actions
  .github/workflows/main.yml
Labels: Status: Needs Review

#189 FIx: Add unique Program name validation
  app/api/dao/program.py
  app/api/resources/organizations.py
  app/api/validations/organization.py
  app/database/models/bit_schema/program.py
  app/messages.py
  tests/programs/test_api_create_program.py
Labels: Category: Coding, Status: Changes Requested

#268 Feat: Add GET endpoint /users/{userId}/personal-background to fetch personal background from userId
  app/api/resources/users.py
  app/database/models/bit_schema/organization.py
  app/database/models/bit_schema/personal_background.py
  app/database/models/bit_schema/program.py
  app/database/models/bit_schema/user_extension.py
  app/database/models/ms_schema/user.py
  app/messages.py
Labels: Category: Coding, Open Source Hack, Status: Changes Requested
