Repository anitab-org/bridge-in-tech-backend, pull requests merged in 2021-03, with the labels that each got.

#202 clean: Removed ".github/ISSUE_TEMPLATES" from the repository
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user-story-task.md
  .github/ISSUE_TEMPLATE/user-story.md
  .github/config.yml
Labels: Category: Documentation/Training, Status: Needs Review, Type: Maintenance

#204 fix: Token expiry check removed
  app/api/request_api_utils.py
Labels: Category: Coding, Status: Changes Requested, Type: Bug

#212 fix: Add link to ENVIRONMENT_VARIABLES.md file
  .github/ENV_SETUP_INSTRUCTION.md
Labels: Category: Documentation/Training, Status: Changes Requested, Type: Maintenance
