Repository anitab-org/bridge-in-tech-backend, pull requests merged in 2021-02, with the labels that each got.

#182 Heroku web client typo fix
  app/api/bit_extension.py
Labels: Category: Documentation/Training, Status: Needs Testing, Type: Bug

#188 Use HTTPStatus code values instead of enum representation in Users API
  app/api/resources/users.py
Labels: Category: Documentation/Training, Status: Needs Review

#199 Updated PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Category: Documentation/Training, Type: Maintenance

#200 Feat: Migrate documentation from wiki to docusaurus.
  README.md
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/docs/Commit-Message-Style-Guide.md
  docs/docs/Environment-Setup-Instructions.md
  docs/docs/Fork,-Clone-&-Remote.md
  docs/docs/GSoC-2020-Maya-Treacy.md
  docs/docs/Getting-Started.md
  docs/docs/Home.md
  docs/docs/Project-Ideas.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/styles.module.css
  docs/static/.nojekyll
  docs/static/img/favicon.ico
  docs/static/img/logo.png
  docs/yarn.lock
Labels: Category: Documentation/Training, Status: Needs Review, Type: Maintenance
