Repository anitab-org/bridge-in-tech-backend, pull requests merged in 2021-06, with the labels that each got.

#283 refactor : add typehints to program module
  app/api/dao/program.py
Labels: Category: Coding, Status: Ready to Merge, Type: Enhancement

#286 refactor : Add typehints to user module
  app/api/dao/user_extension.py
Labels: Category: Coding, Status: Needs Review

#280 chore: deployed documentation to gh pages
  .github/workflows/documentation.yml
  README.md
  docs/docusaurus.config.js
Labels: Status: Needs Review

#292 Updated organization name in docusaurus config
  docs/docusaurus.config.js
Labels: Status: Needs Review
